### ISSUE TITLE
Fix search bar layout in RTL mode

### ISSUE THREAD

**Issue by mohabdul19** [gnumdk/eolie#278]
![screenshot_ _](https://user-images.githubusercontent.com/7888581/32383071-0cfca886-c0c8-11e7-8949-a8ca21d302c5.png)

#### Environment
- Eolie version: 0.9.9
- GNOME/GTK+ versions: (Flatpak package) org.gnome.Platform/x86_64/3.26
- GNU/Linux distribution: Archlinux

**Comment by gnumdk** [comment]
I do not understand how it works in a standard Gtk.Entry. All is reverted but text is always LTR! WTF?

**Comment by mohabdul19** [comment]
I tried to fix this issue by using GTK inspector:
1. Set `margin-end` of `icon_grid` to 5px
2. Copy this to CSS Tab:
```css
.uribar:dir(rtl) {
  padding-left: 53px;
  padding-right: 8px;
}

.placeholder:dir(rtl) {
  margin-left: 0px;
  margin-right: 31px;
}
```
#### Result: It's fixed!
![screenshot_ _](https://user-images.githubusercontent.com/7888581/32396547-b54015d6-c0f6-11e7-9368-59afb481827a.png)
